### ISSUE TITLE
Missing proj-datumgrid

### ISSUE THREAD

**Issue by Nodd** [conda-forge/datumgrid-feedstock#5]
Hi,
It's missing the vanilla proj-datumgrid : http://download.osgeo.org/proj/proj-datumgrid-1.8.zip
It contains files for the whole world which are _not_ included in `datumgrid-world`, like `egm69_15.gtx`.

**Comment by xylar** [comment]
@Nodd, are you sure you are using a version of `proj` that is old enough to need these packages?  The current version or `proj` is 8.2.1 and these packages have not been needed since proj 7.0.0.  I believe you may want to use `proj-data` instead: https://github.com/conda-forge/proj-data-feedstock

I started working on a PR to add the missing data but I don't think we actually want to maintain this outdated approach.

**Comment by Nodd** [comment]
@xylar You're right, I was lost between all the versions on an old installation, until I found this page : https://pyproj4.github.io/pyproj/stable/transformation_grids.html
Sorry for the noise !
